version: '3'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    image: yiyouguisu/envoy_fault-injection:latest
    networks:
      - envoy_fault_injection_network
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"

  service1: 
    build:
      context: ./
      dockerfile: Dockerfile-service1
    networks:
      envoy_fault_injection_network:
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
networks:
  envoy_fault_injection_network: {}
